/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'baldur' at '10/20/15 10:44 AM' with Gradle 2.7
 *
 * @author baldur, @date 10/20/15 10:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
